[package]
name = "iprangecheck"
version = "0.1.1"
edition = "2024"

[dependencies]
cidr = { version = "0.3.1", features = ["serde"] }
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
